export const constantsText = {
  errorMsg: 'Something went wrong. Please, try again',
  success: 'success',
  error: 'error',
  loginLink: '/login',
  registerLink: '/register',
  dashboardLink: '/dashboard',
  divTag: 'DIV',
  errorInitialMsg: 'Something went wrong',
  loaderColor: 'inherit',
  deleteTaskMsg: 'Do you want to delete a task',
  simplePopOver: 'simple-popover',
  initialStartTime: '08:00',
  initialFinishTime: '09:00',
  finishTime: '17:00',
  textFieldVariant: 'standard',
  textFieldSize: 'normal',
  textFieldFWId: 'fullWidth',
  textFieldStandard: 'standard-basic',
  inputNameStart: 'startTime',
  inputNameFinish: 'finishTime',
  inputNameTitle: 'title',
  authMenu: 'authMenu',
  authNav: 'authNav',
  minTimeMsg: `Min start time is 08:00`,
  maxTimeMsg: `Max finish time is 17:00`,
  startTimeBiggerFinishTimeMsg: 'Start time is bigger than finish time',
  startTimeSameWithFinishTime: "Start time can't be the same as finish time",
  authMsg: {
    registrationMsgSuccess:
      "You've registered in successfully. Please, log in now",
    registrationMsgError: 'Check your credentials or log in',
    logInMsgSuccess: "You've logged in successfully",
    logInMsgError: ' Check you credentials or register',
  },
};

export const constantsNumbers = {
  startPageDelay: 1000,
  delay: 2000,
  initialTaskItemWidth: 200,
  initialTaskLeftPosition: 50,
};
